SELECT TRIP_START_DATE,
  SM.TRIP_ID,
  SM.GEAR_CODE AS GEAR,
  SM.SPECIES_CODE,
  SPP.SPECIES_COMMON_NAME,
  SPP.SPECIES_SCIENCE_NAME,
  SP.SAMPLE_ID,
  SP.SPECIMEN_ID,
  SP.SPECIMEN_SEX_CODE AS SEX,
  SPECIMEN_AGE AS AGE,
  SP.AGEING_METHOD_CODE AS AGEING_METHOD,
  CAST(ROUND(Best_Length / 10.0, 1) AS DECIMAL(8,1)) AS LENGTH,
  ROUND_WEIGHT AS WEIGHT,
  SP.MATURITY_CODE,
  SM.MATURITY_CONVENTION_CODE,
  MC.MATURITY_CONVENTION_DESC,
  TRIP_SUB_TYPE_CODE,
  SM.SAMPLE_TYPE_CODE,
  SM.SPECIES_CATEGORY_CODE,
  SM.SAMPLE_SOURCE_CODE,
  SM.CATCH_WEIGHT,
  SM.CATCH_COUNT,
  SM.MAJOR_STAT_AREA_CODE,
  MAJOR_STAT_AREA_NAME,
  SM.MINOR_STAT_AREA_CODE
FROM GFBioSQL.dbo.B21_Samples SM
	INNER JOIN GFBioSQL.dbo.B22_Specimens SP ON SM.SAMPLE_ID = SP.SAMPLE_ID
	INNER JOIN GFBioSQL.dbo.SPECIES SPP ON SPP.SPECIES_CODE = SM.SPECIES_CODE
	INNER JOIN GFBioSQL.dbo.Maturity_Convention MC ON SM.MATURITY_CONVENTION_CODE = MC.MATURITY_CONVENTION_CODE
	INNER JOIN GFBioSQL.dbo.FISHING_EVENT FE ON FE.FISHING_EVENT_ID = SM.FISHING_EVENT_ID
	INNER JOIN GFBioSQL.dbo.MAJOR_STAT_AREA MSA ON SM.MAJOR_STAT_AREA_CODE = MSA.MAJOR_STAT_AREA_CODE
	LEFT OUTER JOIN GFBioSQL.dbo.MATURITY_DESCRIPTION MD ON SM.MATURITY_CONVENTION_CODE = MD.MATURITY_CONVENTION_CODE AND SP.MATURITY_CODE = MD.MATURITY_CODE AND SP.SPECIMEN_SEX_CODE = MD.SPECIMEN_SEX_CODE
WHERE TRIP_SUB_TYPE_CODE IN (1, 4, 5) AND
  SM.SAMPLE_TYPE_CODE IN (0, 1, 2, 5, 6, 7, 8) AND
  SM.FE_SUB_LEVEL_ID IS NULL AND
  SM.SPECIES.CODE IN 439 AND
AND SM.MAJOR_STAT_AREA_CODE BETWEEN 3 AND 7
AND AGEING_METHOD_CODE = 3
ORDER BY YEAR(TRIP_START_DATE)

