db_connection <- function(server = "DFBCV9TWVASP001", database = "GFBioSQL") {
  DBI::dbConnect(odbc::odbc(), driver = "SQL Server",
    server = server, database = database)
}

con <- db_connection()

d <- get_sql_data("
  SELECT * FROM SURVEY_SERIES")
saveRDS(d, file = "survey_series.rds")

d <- DBI::dbGetQuery(db_connection(database = "GFBioSQL"),"
  SELECT TRIP_START_DATE,
    S.SURVEY_SERIES_ID,
    SPECIMEN_SEX_CODE AS SEX,
    SPECIMEN_AGE AS AGE,
    CAST(ROUND(Best_Length / 10.0, 1) AS DECIMAL(8,1)) AS LENGTH,
    MATURITY_CODE,
    MATURITY_CONVENTION_DESC,
    MATURITY_CONVENTION_MAXVALUE,
    ROUND_WEIGHT AS WEIGHT,
    SM.SPECIES_CODE, SPP.SPECIES_COMMON_NAME, SPP.SPECIES_SCIENCE_NAME,
    SM.SPECIES_CATEGORY_CODE,
    TRIP_SUB_TYPE_CODE
  FROM GFBioSQL.dbo.SURVEY S
    INNER JOIN GFBioSQL.dbo.SURVEY_GROUPING SG ON S.SURVEY_ID = SG.SURVEY_ID
    INNER JOIN GFBioSQL.dbo.FISHING_EVENT_GROUPING FEG ON SG.GROUPING_CODE = FEG.GROUPING_CODE
    INNER JOIN GFBioSQL.dbo.B21_Samples SM ON FEG.FISHING_EVENT_ID = SM.FISHING_EVENT_ID
    INNER JOIN GFBioSQL.dbo.TRIP_SURVEY TS ON S.SURVEY_ID = TS.SURVEY_ID
    INNER JOIN GFBioSQL.dbo.FISHING_EVENT FE ON 
      TS.TRIP_ID = FE.TRIP_ID AND FE.FISHING_EVENT_ID = SM.FISHING_EVENT_ID
    INNER JOIN GFBioSQL.dbo.B22_Specimens SP ON SM.SAMPLE_ID = SP.SAMPLE_ID
    INNER JOIN GFBioSQL.dbo.SPECIES SPP ON SPP.SPECIES_CODE = SM.SPECIES_CODE
    INNER JOIN GFBioSQL.dbo.Maturity_Convention MC ON SM.MATURITY_CONVENTION_CODE = MC.MATURITY_CONVENTION_CODE
  WHERE SPECIMEN_SEX_CODE IN (1, 2) AND TRIP_SUB_TYPE_CODE IN (2, 3) 
  ORDER BY SM.SPECIES_CODE, S.SURVEY_SERIES_ID, TRIP_START_DATE")
head(d)
nrow(d)
# WHERE S.SURVEY_SERIES_ID IN (1, 3, 4, 6, 14, 16, 22, 36) AND
saveRDS(d, file = "all-survey-bio.rds")

# TRIP_SUB_TYPE_CODE diff!!!!!!!!
d <- DBI::dbGetQuery(db_connection(database = "GFBioSQL"),"
  SELECT TRIP_START_DATE,
  SPECIMEN_SEX_CODE AS SEX,
  SPECIMEN_AGE AS AGE,
  CAST(ROUND(Best_Length / 10.0, 1) AS DECIMAL(8,1)) AS LENGTH,
  MATURITY_CODE,
  MATURITY_CONVENTION_DESC,
  MATURITY_CONVENTION_MAXVALUE,
  ROUND_WEIGHT AS WEIGHT,
  SM.SPECIES_CODE, SPP.SPECIES_COMMON_NAME, SPP.SPECIES_SCIENCE_NAME,
  SM.SPECIES_CATEGORY_CODE,
  TRIP_SUB_TYPE_CODE

 FROM GFBioSQL.dbo.B21_Samples SM
  INNER JOIN GFBioSQL.dbo.B22_Specimens SP ON SM.SAMPLE_ID = SP.SAMPLE_ID
  INNER JOIN GFBioSQL.dbo.SPECIES SPP ON SPP.SPECIES_CODE = SM.SPECIES_CODE
  INNER JOIN GFBioSQL.dbo.Maturity_Convention MC ON SM.MATURITY_CONVENTION_CODE = MC.MATURITY_CONVENTION_CODE

  WHERE TRIP_SUB_TYPE_CODE NOT IN (2, 3) AND SPECIMEN_SEX_CODE IN (1, 2)
  ORDER BY SM.SPECIES_CODE, TRIP_START_DATE")
head(d)
nrow(d)
saveRDS(d, file = "all-commercial-bio.rds")

# catch effort:
d <- DBI::dbGetQuery(db_connection(database = "GFFOS"),
  "SELECT DATABASE_NAME,
     FISHERY_SECTOR,
     GEAR,
     BEST_DATE,
     FE_START_DATE, FE_END_DATE,
     SPECIES_SCIENTIFIC_NAME, SPECIES_COMMON_NAME,
     LANDED_KG, DISCARDED_KG, LANDED_PCS, DISCARDED_PCS
  FROM GFFOS.dbo.GF_MERGED_CATCH MC
  INNER JOIN GFFOS.dbo.SPECIES SP ON SP.SPECIES_CODE = MC.SPECIES_CODE
  ORDER BY BEST_DATE, SPECIES_COMMON_NAME")
head(d)
nrow(d)
saveRDS(d, file = "all-catches.rds")

# biomass indices:

d <- DBI::dbGetQuery(db_connection(database = "GFBioSQL"),
" SELECT BH.SURVEY_YEAR AS year,
      CAST(ROUND(ISNULL(BD.BIOMASS,0), 2) AS DECIMAL(15,2)) AS biomass,
  CAST(ROUND(ISNULL(BD.BOOT_LOWER_CI,0), 2) AS DECIMAL(15,2)) AS lowerci,
  CAST(ROUND(ISNULL(BD.BOOT_UPPER_CI,0), 2) AS DECIMAL(15,2)) AS upperci,
  CAST(ROUND(ISNULL(BD.BOOT_RE,0), 5) AS DECIMAL(8,5)) AS re,
  ISNULL(BD.NUM_SETS,0) AS num_sets,
  ISNULL(BD.NUM_POS_SETS,0) AS num_pos_sets,
  BD.SURVEY_SERIES_ID,
  SS.SURVEY_SERIES_DESC,
  SP.SPECIES_COMMON_NAME, SP.SPECIES_SCIENCE_NAME
  FROM (
  SELECT BH.SURVEY_YEAR,
  BH.SURVEY_SERIES_ID,
  BH.BOOT_ID
  FROM GFBioSQL.dbo.BOOT_HEADER BH
  WHERE ACTIVE_IND = 1) BH
  LEFT JOIN (
  SELECT BH.BOOT_ID,
  BD.SURVEY_SERIES_ID,
  BD.SPECIES_CODE,
  BD.BIOMASS,
  BD.BOOT_LOWER_CI,
  BD.BOOT_UPPER_CI,
  BD.BOOT_RE,
  BD.NUM_SETS,
  BD.NUM_POS_SETS
  FROM GFBioSQL.dbo.BOOT_HEADER BH
  INNER JOIN GFBioSQL.dbo.BOOT_DETAIL BD ON
  BH.BOOT_ID = BD.BOOT_ID
  WHERE BH.ACTIVE_IND = 1) BD ON BH.BOOT_ID = BD.BOOT_ID
  INNER JOIN GFBioSQL.dbo.SPECIES SP ON SP.SPECIES_CODE = BD.SPECIES_CODE
  INNER JOIN GFBioSQL.dbo.SURVEY_SERIES SS ON SS.SURVEY_SERIES_ID = BD.SURVEY_SERIES_ID

  ORDER BY BH.SURVEY_YEAR    
")
head(d)
nrow(d)
saveRDS(d, file = "all-boot-biomass-indices.rds")