---
title: "Commercial CPUE"
author: "Sean Anderson"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Commercial CPUE}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE # temp
)
```

```{r, include=FALSE}
d <- readRDS("../data-cache/gf_merged_catch_1996_onwards.rds") # TODO deal with
library("PBSsynopsis")
```

```{r, eval=FALSE}
library("PBSsynopsis")
d <- get_cpue_index(gear = "bottom trawl")
```

```{r, warnings=FALSE, message=FALSE}
walleye <- tidy_cpue_index(d,
  species_common = "walleye pollock",
  area_grep_pattern = "5[CDE]+",
  min_positive_tows = 100,
  min_positive_trips = 4,
  min_yrs_with_trips = 4)
```

```{r fit-cpue-model, warnings=FALSE, message=FALSE, results='hide', cache=TRUE}
m <- fit_cpue_index(walleye)
```

```{r, warnings=FALSE, message=FALSE, fig.width=9, fig.height=9}
plot_cpue_index_coefs(m)
```

```{r, warnings=FALSE, message=FALSE, fig.width=9, fig.height=3}
predict_cpue_index(m) %>%
  plot_cpue_index()

predict_cpue_index(m, center = TRUE) %>%
  plot_cpue_index()
```

```{r, warnings=FALSE, message=FALSE, fig.width=4, fig.height=2.5}
predict_cpue_index(m, center = TRUE) %>%
  plot_cpue_index(all_models = FALSE)
```

```{r cpue-jk, warnings=FALSE, message=FALSE, fig.width=8, fig.height=4, cache=TRUE}
jackknife_cpue_index(m)
```
