SELECT GFBioSQL.dbo.SPECIMEN_AGE.SPECIMEN_ID, YEAR(SM.SAMPLE_DATE) AS YEAR, C.SPECIES_CODE AS SPECIES_CODE, GFBioSQL.dbo.SPECIMEN_AGE.AGE_READING_TYPE_CODE,
                  GFBioSQL.dbo.AGEING_METHOD.AGEING_METHOD_DESC, GFBioSQL.dbo.SPECIMEN_AGE.SPECIMEN_AGE, GFBioSQL.dbo.SPECIMEN_AGE.MINIMUM_AGE,
                  GFBioSQL.dbo.SPECIMEN_AGE.MAXIMUM_AGE, GFBioSQL.dbo.SPECIMEN_AGE.EMPLOYEE_ID, GFBioSQL.dbo.SPECIMEN_AGE.AGE_READING_ID, SPECIMEN_AGE.AGEING_METHOD_CODE AS METHOD_CODE
FROM   GFBioSQL.dbo.AGEING_METHOD INNER JOIN
                  GFBioSQL.dbo.SPECIMEN_AGE ON
                  GFBioSQL.dbo.AGEING_METHOD.AGEING_METHOD_CODE = GFBioSQL.dbo.SPECIMEN_AGE.AGEING_METHOD_CODE LEFT OUTER JOIN
                  GFBioSQL.dbo.CATCH_SAMPLE INNER JOIN
                  GFBioSQL.dbo.SAMPLE SM ON GFBioSQL.dbo.CATCH_SAMPLE.SAMPLE_ID = SM.SAMPLE_ID INNER JOIN
                  GFBioSQL.dbo.CATCH C ON GFBioSQL.dbo.CATCH_SAMPLE.CATCH_ID = C.CATCH_ID ON
                  GFBioSQL.dbo.SPECIMEN_AGE.SAMPLE_ID = SM.SAMPLE_ID
WHERE  (GFBioSQL.dbo.SPECIMEN_AGE.AGE_READING_TYPE_CODE IN (2,3)) 
-- insert species here
ORDER BY SPECIMEN_ID
