SELECT GFBioSQL.dbo.SPECIMEN_AGE.SPECIMEN_ID, GFBioSQL.dbo.CATCH.SPECIES_CODE, GFBioSQL.dbo.SPECIMEN_AGE.AGE_READING_TYPE_CODE,
                  GFBioSQL.dbo.AGEING_METHOD.AGEING_METHOD_DESC, GFBioSQL.dbo.SPECIMEN_AGE.SPECIMEN_AGE, GFBioSQL.dbo.SPECIMEN_AGE.MINIMUM_AGE,
                  GFBioSQL.dbo.SPECIMEN_AGE.MAXIMUM_AGE
FROM   GFBioSQL.dbo.AGEING_METHOD INNER JOIN
                  GFBioSQL.dbo.SPECIMEN_AGE ON
                  GFBioSQL.dbo.AGEING_METHOD.AGEING_METHOD_CODE = GFBioSQL.dbo.SPECIMEN_AGE.AGEING_METHOD_CODE LEFT OUTER JOIN
                  GFBioSQL.dbo.CATCH_SAMPLE INNER JOIN
                  GFBioSQL.dbo.SAMPLE ON GFBioSQL.dbo.CATCH_SAMPLE.SAMPLE_ID = GFBioSQL.dbo.SAMPLE.SAMPLE_ID INNER JOIN
                  GFBioSQL.dbo.CATCH ON GFBioSQL.dbo.CATCH_SAMPLE.CATCH_ID = GFBioSQL.dbo.CATCH.CATCH_ID ON
                  GFBioSQL.dbo.SPECIMEN_AGE.SAMPLE_ID = GFBioSQL.dbo.SAMPLE.SAMPLE_ID
WHERE  (GFBioSQL.dbo.SPECIMEN_AGE.AGE_READING_TYPE_CODE = 1)
-- insert species here
ORDER BY SPECIMEN_ID
