--This query only extracts depth and temperature data from sensors deployed on hooks
-- on the HBLL Inside surveys.  CTD data are extracted separately, and are collected
-- approximately 5 m off the bottom (whereas all data on trawl surveys are considered 
-- bottom data).
SELECT YEAR(FE_END_DEPLOYMENT_TIME) AS YEAR
	,SURVEY_SERIES_ID AS SSID
	,SURVEY_DESC 
	,FE.TRIP_ID
	,FE.FISHING_EVENT_ID
	,TIME_STAMP
	,SENSOR_DATA_ATTRIBUTE_DESC AS ATTRIBUTE
	,ROUND(MIN(SD.SENSOR_DATA_VALUE), 0) AS MIN_VALUE
	,ROUND(AVG(SD.SENSOR_DATA_VALUE), 0) AS AVG_VALUE
	,ROUND(MAX(SD.SENSOR_DATA_VALUE), 0) AS MAX_VALUE
	,SENSOR_DATA_UNIT_DESC AS UNIT
FROM FISHING_EVENT FE	
	INNER JOIN TRIP_SURVEY TS ON FE.TRIP_ID = TS.TRIP_ID
	INNER JOIN SURVEY S ON TS.SURVEY_ID = S.SURVEY_ID
	INNER JOIN FISHING_EVENT_SENSOR_DATAFILE FESD ON FE.FISHING_EVENT_ID = FESD.FISHING_EVENT_ID
	INNER JOIN SENSOR_DATA SD ON FESD.SENSOR_DATAFILE_NAME = SD.SENSOR_DATAFILE_NAME
	INNER JOIN SENSOR_DATA_ATTRIBUTE A ON SD.SENSOR_DATA_ATTRIBUTE_CODE = A.SENSOR_DATA_ATTRIBUTE_CODE
	INNER JOIN SENSOR_DATA_UNIT U ON SD.SENSOR_DATA_UNIT_CODE = U.SENSOR_DATA_UNIT_CODE
WHERE SURVEY_SERIES_ID IN (39, 40)  
	AND FE_PARENT_EVENT_ID IS NULL
	AND	SD.SENSOR_DATA_ATTRIBUTE_CODE IN (1, 2, 3, 4) 
	AND SD.SENSOR_DATA_UNIT_CODE IN (1, 2, 5, 7)
	AND FE.FISHING_EVENT_ID =4589988
--NOT SURE WHAT TO USE FOR TIME RESTRICTION HERE - PERHAPS CONSTANT DEPTH?	
--CONSIDERING LOOKING AT VALUES OF ENV VARIABLES AT MAX DEPTH. CHECK THAT THE MIN/MAX/AVG IS WORKING RIGHT IN ALL SENSOR QUERIES.
	AND ORIGINAL_IND = 'Y'
GROUP BY FE_END_DEPLOYMENT_TIME 
	,SURVEY_SERIES_ID
	,SURVEY_DESC
	,FE.TRIP_ID
	,FE.FISHING_EVENT_ID
	,SENSOR_DATA_ATTRIBUTE_DESC
	,SENSOR_DATA_UNIT_DESC
	,FE_BEGIN_DEPLOYMENT_TIME
	,FE_END_RETRIEVAL_TIME
	
	,TIME_STAMP
	order by TIME_STAMP