SELECT YEAR(FE_BEGIN_BOTTOM_CONTACT_TIME) AS YEAR, 
	SURVEY_SERIES_ID AS SSID,
	SURVEY_DESC,
	FESD.FISHING_EVENT_ID, 
	SENSOR_DATA_ATTRIBUTE_DESC AS ATTRIBUTE,
	ROUND(MIN(SD.SENSOR_DATA_VALUE), 0) AS MIN_VALUE,
	ROUND(AVG(SD.SENSOR_DATA_VALUE), 0) AS AVG_VALUE,
	ROUND(MAX(SD.SENSOR_DATA_VALUE), 0) AS MAX_VALUE,
	SENSOR_DATA_UNIT_DESC AS UNIT
FROM  FISHING_EVENT_SENSOR_DATAFILE FESD 
	INNER JOIN SENSOR_DATA SD ON FESD.SENSOR_DATAFILE_NAME = SD.SENSOR_DATAFILE_NAME
	INNER JOIN FISHING_EVENT FE ON FESD.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
	INNER JOIN TRIP_SURVEY TS ON FE.TRIP_ID = TS.TRIP_ID
	INNER JOIN SURVEY S ON TS.SURVEY_ID = S.SURVEY_ID
	INNER JOIN SENSOR_DATA_ATTRIBUTE A ON SD.SENSOR_DATA_ATTRIBUTE_CODE = A.SENSOR_DATA_ATTRIBUTE_CODE
	INNER JOIN SENSOR_DATA_UNIT U ON SD.SENSOR_DATA_UNIT_CODE = U.SENSOR_DATA_UNIT_CODE
WHERE SURVEY_SERIES_ID IN(1, 3, 4, 16)
	AND	SD.SENSOR_DATA_ATTRIBUTE_CODE IN (1, 2, 3, 4) 
	AND SD.SENSOR_DATA_UNIT_CODE IN (1, 2, 5, 7)
	AND TIME_STAMP BETWEEN FE_BEGIN_BOTTOM_CONTACT_TIME AND FE_END_BOTTOM_CONTACT_TIME
-- insert ssid here
-- insert attribute here
GROUP BY SURVEY_SERIES_ID,
	SURVEY_DESC, 
	FESD.SENSOR_DATAFILE_NAME, 
	YEAR(FE_BEGIN_BOTTOM_CONTACT_TIME), 
	FESD.FISHING_EVENT_ID, 
	SENSOR_DATA_ATTRIBUTE_DESC, 
	SENSOR_DATA_UNIT_DESC
