SELECT
	YEAR(C.BEST_DATE) AS YEAR,
	FISHERY_SECTOR,
	VESSEL_REGISTRATION_NUMBER,
	GEAR,
	TRIP_ID,
	FISHING_EVENT_ID,
	LATITUDE AS LAT,
	LONGITUDE AS LON,
	C.SPECIES_CODE,
	SPECIES_SCIENTIFIC_NAME,
	SPECIES_COMMON_NAME,
	LANDED_KG AS LANDED_ROUND_KG,
	LANDED_PCS AS cpue,
	DISCARDED_PCS AS TOTAL_RELEASED_PCS,
	MAJOR_STAT_AREA_CODE
FROM
	GFFOS.dbo.GF_MERGED_CATCH C INNER JOIN
    GFFOS.dbo.SPECIES SP ON C.SPECIES_CODE = SP.SPECIES_CODE
GROUP BY
	GEAR, BEST_DATE,
	FISHERY_SECTOR,
	VESSEL_REGISTRATION_NUMBER,
	TRIP_ID,
	FISHING_EVENT_ID,
    LATITUDE,
	LONGITUDE,
    SPECIES_SCIENTIFIC_NAME,
	SPECIES_COMMON_NAME,
    DISCARDED_PCS,
	LANDED_KG,
	C.SPECIES_CODE,
	MAJOR_STAT_AREA_CODE,
	FE_START_DATE,
	FE_END_DATE,
	LANDED_PCS
HAVING
	(GEAR IN ('HOOK AND LINE','LONGLINE','LONGLINE OR HOOK AND LINE')) AND
    LATITUDE BETWEEN 47.8 AND 55 AND
	LONGITUDE BETWEEN -135 AND -122 AND
	FE_END_DATE > FE_START_DATE AND
	YEAR(FE_START_DATE) = YEAR(FE_END_DATE) AND
	YEAR(BEST_DATE) >= 2008 AND
	ISNULL(LANDED_PCS, 0) > 0
-- insert species here
ORDER BY
	YEAR,
	TRIP_ID,
	FISHING_EVENT_ID
