SELECT YEAR(TRIP_START_DATE) AS year,
	T.TRIP_ID AS tripID,
	FE.FISHING_EVENT_ID AS hookID,
	FE_PARENT_EVENT_ID AS skateID,
    BLOCK_DESIGNATION AS block,
	FE_MAJOR_LEVEL_ID AS "set",
	FE_SUB_LEVEL_ID AS skate,
	FE_MINOR_LEVEL_ID AS hook, 
	C.SPECIES_CODE AS speciesCode,
	SPECIES_COMMON_NAME AS species,
	CATCH_WEIGHT AS catchWeight,
	CATCH_COUNT AS numOnHook,
	HOOK_YIELD_CODE AS hookCode,
	COUNT(FE.FE_MINOR_LEVEL_ID)  AS hooksPerSkate,
	SUM(CASE WHEN HS.HOOK_YIELD_CODE IN (7) THEN 0 ELSE 1 END) AS OLDobsHookPerSkate,
    SUM(CASE WHEN HS.HOOK_YIELD_CODE IN (0,7) THEN 0 ELSE 1 END) AS obsHookPerSkate,
	FE_DIRECTION_OF_SET AS direction,
	--EFFECTIVE_SKATE AS effectSkate,
	HS.HOOK_CONDITION_CODE AS hook_condition_code
  
FROM FISHING_EVENT FE
	INNER JOIN TRIP T ON FE.TRIP_ID = T.TRIP_ID 
	INNER JOIN TRIP_SURVEY TS ON TS.TRIP_ID = T.TRIP_ID
	INNER JOIN SURVEY S ON S.SURVEY_ID = TS.SURVEY_ID
	INNER JOIN FISHING_EVENT_CATCH FEC ON FEC.FISHING_EVENT_ID = FE.FISHING_EVENT_ID AND FEC.TRIP_ID = T.TRIP_ID
	INNER JOIN CATCH C ON C.CATCH_ID = FEC.CATCH_ID
	INNER JOIN HOOK_SPECS HS ON HS.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
	LEFT JOIN IPHC_EFFECTIVE_SKATE ES ON FE.FISHING_EVENT_ID = ES.FISHING_EVENT_ID
	--INNER JOIN IPHC_EFFECTIVE_SKATE ES ON ES.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
	INNER JOIN SPECIES SP ON SP.SPECIES_CODE = C.SPECIES_CODE
	
WHERE SURVEY_SERIES_ID = '14' AND FE_PARENT_EVENT_ID IS NOT NULL

-- insert species here
GROUP BY T.TRIP_START_DATE, T.TRIP_ID, FE.FISHING_EVENT_ID, FE_PARENT_EVENT_ID,
    BLOCK_DESIGNATION,
	FE_MAJOR_LEVEL_ID,
	FE_SUB_LEVEL_ID,
	FE_MINOR_LEVEL_ID, 
	C.SPECIES_CODE ,
	SPECIES_COMMON_NAME,
	CATCH_WEIGHT ,
	CATCH_COUNT,
	HOOK_YIELD_CODE,
	FE_DIRECTION_OF_SET,
	--EFFECTIVE_SKATE,
	HS.HOOK_CONDITION_CODE
ORDER BY year, T.TRIP_ID, FE.FISHING_EVENT_ID

