SELECT TOP (100) PERCENT YEAR(GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.BEST_DATE) AS YEAR, GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.TRIP_ID,  GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.FISHING_EVENT_ID,
                  GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.LAT, GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.LON, 
                  GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.SPECIES_CODE, GFFOS.dbo.SPECIES.SPECIES_SCIENTIFIC_NAME, GFFOS.dbo.SPECIES.SPECIES_COMMON_NAME, 
                  GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.LANDED_ROUND_KG AS LANDED_KG, (GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.SUBLEGAL_RELEASED_COUNT + GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.LEGAL_RELEASED_COUNT) AS RELEASED_PCS
FROM     GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH INNER JOIN
                  GFFOS.dbo.SPECIES ON GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.SPECIES_CODE = GFFOS.dbo.SPECIES.SPECIES_CODE
GROUP BY GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.GEAR, YEAR(GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.BEST_DATE), 
GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.TRIP_ID, GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.FISHING_EVENT_ID,
                  GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.FISHING_EVENT_ID, GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.LAT, GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.LON, 
                  GFFOS.dbo.SPECIES.SPECIES_SCIENTIFIC_NAME, GFFOS.dbo.SPECIES.SPECIES_COMMON_NAME, 
                  (GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.SUBLEGAL_RELEASED_COUNT + GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.LEGAL_RELEASED_COUNT), GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.LANDED_ROUND_KG, 
                 GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.SPECIES_CODE
HAVING (GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.GEAR = 'HOOK AND LINE') AND 
                  (GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.LAT IS NOT NULL) AND (GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH.LON IS NOT NULL) 
ORDER BY YEAR, TRIP_ID, FISHING_EVENT_ID