SELECT
	YEAR(C.BEST_DATE) AS YEAR,
	C.FISHERY_SECTOR,
	C.VESSEL_REGISTRATION_NUMBER,
	C.GEAR,
	C.TRIP_ID,  
	C.FISHING_EVENT_ID,
	C.LAT,
	C.LON,
	C.SPECIES_CODE,
	SP.SPECIES_SCIENTIFIC_NAME,
	SP.SPECIES_COMMON_NAME,
	C.LANDED_ROUND_KG,
	C.LANDED_COUNT AS cpue,
	C.SUBLEGAL_RELEASED_COUNT + C.LEGAL_RELEASED_COUNT AS TOTAL_RELEASED_PCS,
	C.MAJOR_STAT_AREA_CODE
FROM     
	GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH C INNER JOIN
    GFFOS.dbo.SPECIES SP ON C.SPECIES_CODE = SP.SPECIES_CODE 
GROUP BY 
	C.GEAR, C.BEST_DATE,
	C.FISHERY_SECTOR, 
	C.VESSEL_REGISTRATION_NUMBER,
	C.TRIP_ID,
	C.FISHING_EVENT_ID,
    C.LAT,
	C.LON, 
    SP.SPECIES_SCIENTIFIC_NAME,
	SP.SPECIES_COMMON_NAME, 
    C.SUBLEGAL_RELEASED_COUNT + C.LEGAL_RELEASED_COUNT,
	C.LANDED_ROUND_KG,
	C.SPECIES_CODE,
	SP.SPECIES_CODE,
	C.MAJOR_STAT_AREA_CODE,
	START_DATE,
	END_DATE,
	LANDED_COUNT	
HAVING 
	(C.GEAR IN ('HOOK AND LINE','LONGLINE','LONGLINE OR HOOK AND LINE')) AND 
    LAT BETWEEN 47.8 AND 55 AND
	LON BETWEEN -135 AND -122 AND
	END_DATE > START_DATE AND 
	YEAR(START_DATE) = YEAR(END_DATE) AND
	ISNULL(LANDED_COUNT, 0) > 0
-- insert species here
ORDER BY 
	YEAR,
	TRIP_ID,
	FISHING_EVENT_ID
