SELECT YEAR(BEST_DATE) AS YEAR,
	TRIP_ID,
	FISHING_EVENT_ID,
	FE_START_DATE,
	FE_END_DATE,
	SPECIES_CODE,
	GEAR,
	BEST_DEPTH,
	MAJOR_STAT_AREA_CODE,
	LOCALITY_CODE,
	LATITUDE,
	LONGITUDE,
	ISNULL(LANDED_KG, 0),
	ISNULL(DISCARDED_KG, 0)
FROM GFFOS.dbo.GF_MERGED_CATCH
WHERE GEAR IN('MIDWATER TRAWL', 'BOTTOM TRAWL') AND 
	YEAR(BEST_DATE) >=1996 AND FE_START_DATE IS NOT NULL AND 
	FE_END_DATE IS NOT NULL