SELECT TRIP_START_DATE, SP.SPECIMEN_ID,
  SPECIMEN_SEX_CODE AS SEX,
  SPECIMEN_AGE AS AGE,
  CAST(ROUND(Best_Length / 10.0, 1) AS DECIMAL(8,1)) AS LENGTH,
  MATURITY_CODE, MATURITY_CONVENTION_DESC, MATURITY_CONVENTION_MAXVALUE,
  ROUND_WEIGHT AS WEIGHT,
  SM.SPECIES_CODE, SPP.SPECIES_COMMON_NAME, SPP.SPECIES_SCIENCE_NAME,
  SM.SPECIES_CATEGORY_CODE,
  TRIP_SUB_TYPE_CODE, SM.SAMPLE_SOURCE_CODE, SM.SAMPLE_TYPE_CODE, GEAR_CODE,
  SM.CATCH_WEIGHT, SM.CATCH_COUNT
FROM GFBioSQL.dbo.B21_Samples SM
INNER JOIN GFBioSQL.dbo.B22_Specimens SP ON SM.SAMPLE_ID = SP.SAMPLE_ID
INNER JOIN GFBioSQL.dbo.SPECIES SPP ON SPP.SPECIES_CODE = SM.SPECIES_CODE
INNER JOIN GFBioSQL.dbo.Maturity_Convention MC ON 
  SM.MATURITY_CONVENTION_CODE = MC.MATURITY_CONVENTION_CODE
WHERE TRIP_SUB_TYPE_CODE NOT IN (2, 3) AND SPECIMEN_SEX_CODE IN (1, 2) AND (NOT (CATCH_WEIGHT IS NULL AND CATCH_COUNT IS NULL))
ORDER BY TRIP_ID, TRIP_START_DATE

