SELECT SA.SPECIMEN_ID, YEAR(SM.SAMPLE_DATE) AS YEAR, SM.SPECIES_CODE, S.SPECIES_COMMON_NAME, SA.AGE_READING_TYPE_CODE,
                  GFBioSQL.dbo.AGEING_METHOD.AGEING_METHOD_DESC, SA.SPECIMEN_AGE, SA.MINIMUM_AGE,
                  SA.MAXIMUM_AGE, SA.EMPLOYEE_ID, SA.AGE_READING_ID, CASE WHEN SPECIES_COMMON_NAME = 'NORTH PACIFIC SPINY DOGFISH' AND SA.AGEING_METHOD_CODE = 11 THEN SA.AGEING_METHOD_CODE
  	WHEN SPECIES_COMMON_NAME = 'WALLEYE POLLOCK' AND SA.AGEING_METHOD_CODE = 7 THEN SA.AGEING_METHOD_CODE	
	WHEN SPECIES_COMMON_NAME IN('LINGCOD', 'PACIFIC COD') AND SA.AGEING_METHOD_CODE = 6 THEN SA.AGEING_METHOD_CODE 
  	WHEN SPECIES_COMMON_NAME IN ('SHORTRAKER ROCKFISH', 'SHORTSPINE THORNYHEAD', 'LONGSPINE THORNYHEAD') AND SA.AGEING_METHOD_CODE IN (1, 3, 4, 17) THEN  SA.AGEING_METHOD_CODE
	WHEN SPECIES_COMMON_NAME IN ('BIG SKATE',
	'LONGNOSE SKATE',
	'BASKING SHARK',
	'SALMON SHARK',
	'BROWN CAT SHARK',
	'BLUE SHARK',
	'PACIFIC SLEEPER SHARK',
	'ALEUTIAN SKATE',
	'ABYSSAL SKATE',
	'BROAD SKATE',
	'ROUGHTAIL SKATE',
	'SANDPAPER SKATE') AND SA.AGEING_METHOD_CODE = 12 THEN SA.AGEING_METHOD_CODE
	WHEN SPECIES_COMMON_NAME IN ('PACIFIC HAKE', 
	'ROUGHEYE/BLACKSPOTTED ROCKFISH COMPLEX', 
	'PACIFIC OCEAN PERCH',
	'REDBANDED ROCKFISH',
	'SILVERGRAY ROCKFISH',
	'COPPER ROCKFISH',
	'DARKBLOTCHED ROCKFISH',
	'WIDOW ROCKFISH',
	'YELLOWTAIL ROCKFISH',
	'QUILLBACK ROCKFISH',
	'BOCACCIO',	
	'CANARY ROCKFISH',
	'REDSTRIPE ROCKFISH',
	'YELLOWMOUTH ROCKFISH',
	'YELLOWEYE ROCKFISH',
	'SABLEFISH',
	'ARROWTOOTH FLOUNDER',
	'PETRALE SOLE',
	'REX SOLE',
	'SOUTHERN ROCK SOLE',
	'DOVER SOLE',
	'ENGLISH SOLE') AND SA.AGEING_METHOD_CODE IN (1, 3, 17) THEN SA.AGEING_METHOD_CODE END AS AGEING_METHOD,
	CASE WHEN MAJOR_STAT_AREA_CODE ='01' THEN 1 ELSE 0 END AS INSIDE
FROM   GFBioSQL.dbo.AGEING_METHOD 
			INNER JOIN GFBioSQL.dbo.SPECIMEN_AGE SA ON GFBioSQL.dbo.AGEING_METHOD.AGEING_METHOD_CODE = SA.AGEING_METHOD_CODE 
			INNER JOIN GFBioSQL.dbo.B21_Samples SM ON SM.SAMPLE_ID = SA.SAMPLE_ID 
			INNER JOIN GFBioSQL.dbo.SPECIES S ON S.SPECIES_CODE = SM.SPECIES_CODE
WHERE  (SA.AGE_READING_TYPE_CODE IN (2,3)) 
-- insert species here
-- insert inside here
ORDER BY SA.AGEING_METHOD_CODE
