SELECT MC.DATABASE_NAME,
	MC.TRIP_ID,
	MC.VESSEL_REGISTRATION_NUMBER AS VESSEL,
	MONTH(MC.BEST_DATE) AS MONTH,
	YEAR(MC.BEST_DATE) AS YEAR,
	MC.FISHING_EVENT_ID,
	MC.BEST_DATE,
	MC.MAJOR_STAT_AREA_CODE AS MAJ,
	MSA.MAJOR_STAT_AREA_DESCRIPTION,
	MC.MINOR_STAT_AREA_CODE AS MIN,
	MC.LOCALITY_CODE,
	L.LOCALITY_DESCRIPTION,
	LATITUDE,
	LONGITUDE,
	CASE WHEN MC.DATABASE_NAME = 'GFCatch' THEN G.Gear_Type
		ELSE MC.GEAR END AS 'GEAR',
	CASE WHEN MC.DATABASE_NAME = 'GFCatch' THEN E.Time
		ELSE
			(CASE WHEN MC.BEST_DATE < '2014-10-08' AND
			(CONVERT(VARCHAR(8),CAST(MC.FE_END_DATE AS TIME)) = '23:59:00' OR
				CONVERT(VARCHAR(8),CAST(MC.FE_START_DATE AS TIME)) = '00:01:00')
		THEN 0
		ELSE CONVERT(DECIMAL,DATEDIFF(N,MC.FE_START_DATE, MC.FE_END_DATE))/60
		END) END AS HOURS_FISHED,
	MC.BEST_DEPTH AS BEST_DEPTH_M,
	MC.SPECIES_CODE,
	S.SPECIES_COMMON_NAME,
	COALESCE(MC.LANDED_KG,0) AS LANDED_KG,
	COALESCE(MC.DISCARDED_KG,0) AS DISCARDED_KG,
	COALESCE(MC.LANDED_KG,0)+COALESCE(MC.DISCARDED_KG,0) AS TOTCATCH_KG,
	TS.SPECIES_CODE AS TARGET_SPECIES
FROM GFFOS.dbo.GF_MERGED_CATCH MC
	INNER JOIN GFFOS.dbo.MAJOR_STAT_AREA MSA ON MC.MAJOR_STAT_AREA_CODE = MSA.MAJOR_STAT_AREA_CODE
	LEFT JOIN GFFOS.dbo.LOCALITY L ON MC.LOCALITY_CODE = L.LOCALITY_CODE AND MC.MAJOR_STAT_AREA_CODE = L.MAJOR_STAT_AREA_CODE AND MC.MINOR_STAT_AREA_CODE = L.MINOR_STAT_AREA_CODE
	LEFT JOIN GFCatch.dbo.B2_Events E ON MC.TRIP_ID = E.Trip AND CAST(MC.FISHING_EVENT_ID AS BIGINT) = E.Event
	LEFT JOIN GFCatch.dbo.C_Gear G ON E.Gear = G.Gear
	LEFT JOIN GFCatch.dbo.B1_Trips T ON MC.Trip_ID = T.Trip
	LEFT JOIN PacHarvest.dbo.B3_Fishing_Events PHFE ON MC.TRIP_ID = PHFE.OBFL_HAIL_IN_NO AND CAST(MC.FISHING_EVENT_ID AS BIGINT) = PHFE.OBFL_SET_NO
	LEFT JOIN GFFOS.dbo.GF_FE_TRAWL_SPECS TRSP ON CAST(MC.FISHING_EVENT_ID AS BIGINT) = TRSP.FISHING_EVENT_ID
	LEFT JOIN GFFOS.dbo.SPECIES S ON S.SPECIES_CODE = MC.SPECIES_CODE
	LEFT JOIN GFFOS.dbo.GF_FE_TARGET_SPECIES TS ON MC.FISHING_EVENT_ID = TS.FISHING_EVENT_ID
WHERE
	FISHERY_SECTOR = 'GROUNDFISH TRAWL' AND
	MC.MAJOR_STAT_AREA_CODE IN ('03', '04', '05','06','07','08','09') AND
	TRIP_ID NOT IN (43506, 44573, 44639, 44692, 46283, 48856, 49161, 49216, 49304, 52900, 53340, 53380, 50437, 54860, 54861) AND

	CASE WHEN MC.DATABASE_NAME = 'GFCatch' THEN Source ELSE 1 END IN (1, 2) AND

	CASE WHEN MC.DATABASE_NAME = 'GFCatch' THEN G.Gear_Type
		ELSE MC.GEAR END NOT IN ('Shrimp trawl', 'Gillnet drum trawl', 'Danish seine trawl') AND

	CASE WHEN MC.DATABASE_NAME = 'GFCatch' THEN E.Time
		ELSE
			(CASE WHEN MC.BEST_DATE < '2018-10-08' AND
			(CONVERT(VARCHAR(8),CAST(MC.FE_END_DATE AS TIME)) = '23:59:00' OR
				CONVERT(VARCHAR(8),CAST(MC.FE_START_DATE AS TIME)) = '00:01:00')
		THEN 0
		ELSE CONVERT(DECIMAL,DATEDIFF(N,MC.FE_START_DATE, MC.FE_END_DATE))/60
		END) END  >0 AND

	CASE WHEN MC.DATABASE_NAME = 'PacHarvest' THEN OBFL_FE_SUCCESS_CDE ELSE 0 END IN (0, 1) AND
	CASE WHEN MC.DATABASE_NAME = 'GFFOS' THEN TRSP.SUCCESS_CODE ELSE 0 END IN (0, 11710, 11711)

	-- insert species here

