SELECT YEAR(FE_BEGIN_RETRIEVAL_TIME) AS YEAR, 
	SURVEY_SERIES_ID AS SSID,
	SURVEY_DESC,
	FESD.FISHING_EVENT_ID, 
	SENSOR_DATA_ATTRIBUTE_DESC AS ATTRIBUTE,
	MIN(TIME_STAMP) AS START_TIME,
	MAX(TIME_STAMP) AS END_TIME,
	COUNT(SD.SENSOR_DATA_VALUE) AS COUNT,
	CASE WHEN SD.SENSOR_DATA_ATTRIBUTE_CODE = 1 THEN ISNULL(MIN_TEMP_SBE39, MIN_TEMP_SBE19plus) ELSE
		MIN(SD.SENSOR_DATA_VALUE) END AS 'MIN',
	CASE WHEN SD.SENSOR_DATA_ATTRIBUTE_CODE = 1 THEN ISNULL(AVG_TEMP_SBE39, AVG_TEMP_SBE19plus) ELSE
		AVG(SD.SENSOR_DATA_VALUE) END AS 'AVG',
	CASE WHEN SD.SENSOR_DATA_ATTRIBUTE_CODE = 1 THEN ISNULL(MAX_TEMP_SBE39, MAX_TEMP_SBE19plus) ELSE
		MAX(SD.SENSOR_DATA_VALUE) END AS 'MAX',
	CASE SENSOR_DATA_UNIT_ABBR WHEN '(¿C)' THEN 'C' WHEN 'ml/L' THEN 'mlpL' WHEN 'S/m' THEN 'Spm' ELSE SENSOR_DATA_UNIT_ABBR END AS UNIT
FROM  FISHING_EVENT_SENSOR_DATAFILE FESD 
	INNER JOIN SENSOR_DATA SD ON FESD.SENSOR_DATAFILE_NAME = SD.SENSOR_DATAFILE_NAME
	INNER JOIN FISHING_EVENT FE ON FESD.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
	INNER JOIN TRIP_SURVEY TS ON FE.TRIP_ID = TS.TRIP_ID
	INNER JOIN SURVEY S ON TS.SURVEY_ID = S.SURVEY_ID
	INNER JOIN SENSOR_DATA_ATTRIBUTE A ON SD.SENSOR_DATA_ATTRIBUTE_CODE = A.SENSOR_DATA_ATTRIBUTE_CODE
	INNER JOIN SENSOR_DATA_UNIT U ON SD.SENSOR_DATA_UNIT_CODE = U.SENSOR_DATA_UNIT_CODE
	INNER JOIN SENSOR_FILE_TYPE SFT ON SD.SENSOR_FILE_TYPE_CODE = SFT.SENSOR_FILE_TYPE_CODE
	INNER JOIN SENSOR SC ON SFT.SENSOR_CODE = SC.SENSOR_CODE
	INNER JOIN 
		(SELECT
			FESD.FISHING_EVENT_ID, 
			SENSOR_DATA_ATTRIBUTE_CODE AS ATTRIBUTE,
			MIN(CASE WHEN SFT.SENSOR_CODE = 2 THEN SENSOR_DATA_VALUE ELSE NULL END) AS MIN_TEMP_SBE39,
			AVG(CASE WHEN SFT.SENSOR_CODE = 2 THEN SENSOR_DATA_VALUE ELSE NULL END) AS AVG_TEMP_SBE39,
			MAX(CASE WHEN SFT.SENSOR_CODE = 2 THEN SENSOR_DATA_VALUE ELSE NULL END) AS MAX_TEMP_SBE39,
			MIN(CASE WHEN SFT.SENSOR_CODE = 3 THEN SENSOR_DATA_VALUE ELSE NULL END) AS MIN_TEMP_SBE19plus,
			AVG(CASE WHEN SFT.SENSOR_CODE = 3 THEN SENSOR_DATA_VALUE ELSE NULL END) AS AVG_TEMP_SBE19plus,
			MAX(CASE WHEN SFT.SENSOR_CODE = 3 THEN SENSOR_DATA_VALUE ELSE NULL END) AS MAX_TEMP_SBE19plus
		FROM  FISHING_EVENT_SENSOR_DATAFILE FESD 
			INNER JOIN SENSOR_DATA SD ON FESD.SENSOR_DATAFILE_NAME = SD.SENSOR_DATAFILE_NAME
			INNER JOIN FISHING_EVENT FE ON FESD.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
			INNER JOIN TRIP_SURVEY TS ON FE.TRIP_ID = TS.TRIP_ID
			INNER JOIN SURVEY S ON TS.SURVEY_ID = S.SURVEY_ID
			INNER JOIN SENSOR_FILE_TYPE SFT ON SD.SENSOR_FILE_TYPE_CODE = SFT.SENSOR_FILE_TYPE_CODE
		WHERE SENSOR_DATA_ATTRIBUTE_CODE = 1
			AND SENSOR_DATA_VALUE IS NOT NULL 
			AND ORIGINAL_IND = 'Y'
			AND TIME_STAMP BETWEEN FE_BEGIN_BOTTOM_CONTACT_TIME AND FE_END_BOTTOM_CONTACT_TIME
		GROUP BY FESD.FISHING_EVENT_ID, 
			SD.SENSOR_DATA_ATTRIBUTE_CODE
		) T ON FESD.FISHING_EVENT_ID = T.FISHING_EVENT_ID
WHERE SURVEY_SERIES_ID IN (1, 2, 3, 4, 16)  
	AND ORIGINAL_IND = 'Y'
	AND TIME_STAMP BETWEEN FE_BEGIN_BOTTOM_CONTACT_TIME AND FE_END_BOTTOM_CONTACT_TIME AND SD.SENSOR_DATA_ATTRIBUTE_CODE = 1
-- insert ssid here
-- insert attribute here
	AND SD.SENSOR_DATA_UNIT_CODE NOT IN(3) -- Remove volts as possible DO unit
GROUP BY YEAR(FE_BEGIN_RETRIEVAL_TIME), 
	SURVEY_SERIES_ID,
	SURVEY_DESC,
	FESD.FISHING_EVENT_ID, 
	SD.SENSOR_DATA_ATTRIBUTE_CODE,
	SENSOR_DATA_ATTRIBUTE_DESC, 
	SENSOR_DATA_UNIT_ABBR,
	MIN_TEMP_SBE39,
	MIN_TEMP_SBE19plus,
	AVG_TEMP_SBE39,
	AVG_TEMP_SBE19plus,
	MAX_TEMP_SBE39,
	MAX_TEMP_SBE19plus

	ORDER BY FISHING_EVENT_ID