SELECT BH.SURVEY_YEAR AS year,
  CAST(ROUND(ISNULL(BD.BIOMASS,0), 2) AS DECIMAL(15,2)) AS biomass,
  CAST(ROUND(ISNULL(BD.BOOT_LOWER_CI,0), 2) AS DECIMAL(15,2)) AS lowerci,
  CAST(ROUND(ISNULL(BD.BOOT_UPPER_CI,0), 2) AS DECIMAL(15,2)) AS upperci,
  CAST(ROUND(ISNULL(BD.BOOT_RE,0), 5) AS DECIMAL(8,5)) AS re,
  ISNULL(BD.NUM_SETS,0) AS num_sets,
  ISNULL(BD.NUM_POS_SETS,0) AS num_pos_sets,
  BD.SURVEY_SERIES_ID,
   CASE WHEN SURVEY_SERIES_ALT_DESC IS NULL THEN SURVEY_SERIES_TYPE_ALT_DESC 
	WHEN SURVEY_SERIES_TYPE_ALT_DESC IS NULL THEN SURVEY_SERIES_ALT_DESC 
	ELSE (SURVEY_SERIES_TYPE_ALT_DESC + ' ' + SURVEY_SERIES_ALT_DESC) 
	END AS SURVEY_ABBREV,
  SS.SURVEY_SERIES_DESC,
  SP.SPECIES_COMMON_NAME, 
  SP.SPECIES_SCIENCE_NAME
FROM (
  SELECT BH.SURVEY_YEAR, BH.SURVEY_SERIES_ID, BH.BOOT_ID
  FROM GFBioSQL.dbo.BOOT_HEADER BH
  WHERE ACTIVE_IND = 1) BH
	LEFT JOIN (
		SELECT BH.BOOT_ID, BD.SURVEY_SERIES_ID, BD.SPECIES_CODE,
			BD.BIOMASS, BD.BOOT_LOWER_CI, BD.BOOT_UPPER_CI,
			BD.BOOT_RE, BD.NUM_SETS, BD.NUM_POS_SETS
		FROM GFBioSQL.dbo.BOOT_HEADER BH
			INNER JOIN GFBioSQL.dbo.BOOT_DETAIL BD ON
			BH.BOOT_ID = BD.BOOT_ID
		WHERE BH.ACTIVE_IND = 1) BD ON BH.BOOT_ID = BD.BOOT_ID
	INNER JOIN GFBioSQL.dbo.SPECIES SP ON SP.SPECIES_CODE = BD.SPECIES_CODE
	INNER JOIN GFBioSQL.dbo.SURVEY_SERIES SS ON
		SS.SURVEY_SERIES_ID = BD.SURVEY_SERIES_ID
	INNER JOIN GFBioSQL.dbo.SURVEY_SERIES_TYPE SST ON 
		SST.SURVEY_SERIES_TYPE_CODE = SS.SURVEY_SERIES_TYPE_CODE
-- insert species here
-- insert ssid here
ORDER BY BH.SURVEY_YEAR
