SELECT
  DATABASE_NAME,
  MC.TRIP_ID,
  FISHING_EVENT_ID,
  FISHERY_SECTOR,
  TRIP_TYPE_DESCRIPTION AS TRIP_TYPE,
  GEAR,
  BEST_DATE,
  FE_START_DATE,
  FE_END_DATE,
  SPECIES_SCIENTIFIC_NAME,
  SPECIES_COMMON_NAME,
  LANDED_KG,
  CASE WHEN GEAR IN ('TRAP', 'HOOK AND LINE', 'MIDWATER TRAWL') AND YEAR(BEST_DATE) < 2006 THEN 0 
	WHEN GEAR IN ('BOTTOM TRAWL', 'UNKNOWN TRAWL') AND YEAR(BEST_DATE) <1996 THEN 0 
	ELSE DISCARDED_KG END AS DISCARDED_KG,
  LANDED_PCS,
  DISCARDED_PCS,
  MC.MAJOR_STAT_AREA_CODE,
  MC.MINOR_STAT_AREA_CODE,
	MSA.MAJOR_STAT_AREA_NAME,
  VESSEL_NAME,
  VESSEL_REGISTRATION_NUMBER
FROM GFFOS.dbo.GF_MERGED_CATCH MC
	INNER JOIN GFFOS.dbo.SPECIES SP ON SP.SPECIES_CODE = MC.SPECIES_CODE
	INNER JOIN GFBioSQL.dbo.MAJOR_STAT_AREA MSA ON MC.MAJOR_STAT_AREA_CODE = MSA.MAJOR_STAT_AREA_CODE
	LEFT JOIN (SELECT 
		TRIP_ID,
		TRIP_TYPE_DESCRIPTION
	FROM GFFOS.dbo.GF_TRIP_FISHERY TF
		INNER JOIN GFFOS.dbo.TRIP_TYPE TT ON TF.TRIP_TYPE_CODE = TT.TRIP_TYPE_CODE
	WHERE TF.TRIP_TYPE_CODE IN (12762, 12763, 12764, 12765, 12766)) A ON CAST (MC.TRIP_ID AS VARCHAR) = CAST (A.TRIP_ID AS VARCHAR)
-- insert species here
ORDER BY GEAR, BEST_DATE, SPECIES_COMMON_NAME
