SELECT SURVEY_SERIES_DESC AS Survey,
	MIN(YEAR(TRIP_START_DATE)) AS "First_Year",
	MAX(YEAR(TRIP_START_DATE)) AS "Last_Year",
	COUNT(DISTINCT(YEAR(TRIP_START_DATE))) AS "Surveys_Conducted", 
	ISNULL(A.COUNT,0) AS "Surveys_Conducted_Since_2008"
FROM GFBioSQL.dbo.SURVEY_SERIES SS
	INNER JOIN GFBioSQL.dbo.SURVEY S ON S.SURVEY_SERIES_ID = SS.SURVEY_SERIES_ID
	INNER JOIN GFBioSQL.dbo.TRIP_SURVEY TS ON TS.SURVEY_ID = S.SURVEY_ID
	INNER JOIN GFBioSQL.dbo.TRIP T ON T.TRIP_ID = TS.TRIP_ID
    INNER JOIN GFBioSQL.dbo.SURVEY_SERIES_TYPE SST ON SST.SURVEY_SERIES_TYPE_CODE = SS.SURVEY_SERIES_TYPE_CODE
	LEFT JOIN (
	SELECT SURVEY_SERIES_ID, COUNT(DISTINCT(YEAR(TRIP_START_DATE))) AS COUNT 
	FROM GFBioSQL.dbo.SURVEY S 
		INNER JOIN GFBioSQL.dbo.TRIP_SURVEY TS ON TS.SURVEY_ID = S.SURVEY_ID
		INNER JOIN GFBioSQL.dbo.TRIP T ON T.TRIP_ID = TS.TRIP_ID 
	WHERE YEAR(TRIP_START_DATE) >2007 AND
	S.SURVEY_SERIES_ID NOT IN(0,1,3,4,14,16,22,36) AND ORIGINAL_IND = 'Y'
	GROUP BY SURVEY_SERIES_ID) A ON A.SURVEY_SERIES_ID = S.SURVEY_SERIES_ID
WHERE S.SURVEY_SERIES_ID NOT IN(0,1,3,4,14,16,22,36) AND ORIGINAL_IND = 'Y'


GROUP BY S.SURVEY_SERIES_ID, SURVEY_SERIES_DESC, SURVEY_SERIES_HISTORIC_DESC, A.COUNT
ORDER BY S.SURVEY_SERIES_ID
