SELECT A.TRIP_ID, TRIP_START_DATE,
A.SPECIMEN_ID, A.SAMPLE_ID,
  A.SEX,
  A.AGE,
  A.LENGTH,
  A.MATURITY_CONVENTION_CODE, 
  MATURITY_CODE,
  A.WEIGHT,
  A.SPECIES_CODE, A.SPECIES_COMMON_NAME, A.SPECIES_SCIENCE_NAME,
  A.SPECIES_CATEGORY_CODE,
  TRIP_SUB_TYPE_CODE, A.SAMPLE_SOURCE_CODE, A.SAMPLE_TYPE_CODE, A.GEAR_CODE,
  A.USABILITY_CODE,
  A.CATCH_WEIGHT, A.CATCH_COUNT,
  CASE WHEN A.MATURITY_CODE >= B.MATURE_AT THEN 'MATURE' ELSE 'IMMATURE' END AS MATURITY

FROM
(SELECT SM.TRIP_ID, TRIP_START_DATE,
SP.SPECIMEN_ID, SP.SAMPLE_ID,
  SPECIMEN_SEX_CODE AS SEX,
  SPECIMEN_AGE AS AGE,
  CAST(ROUND(Best_Length / 10.0, 1) AS DECIMAL(8,1)) AS LENGTH,
  MATURITY_CODE, SM.MATURITY_CONVENTION_CODE,
  ROUND_WEIGHT AS WEIGHT,
  SM.SPECIES_CODE, SPP.SPECIES_COMMON_NAME, SPP.SPECIES_SCIENCE_NAME,
  SM.SPECIES_CATEGORY_CODE,
  TRIP_SUB_TYPE_CODE, SM.SAMPLE_SOURCE_CODE, SM.SAMPLE_TYPE_CODE, SM.GEAR_CODE,
  CASE FE.GEAR_CODE WHEN 1 THEN TRSP.USABILITY_CODE WHEN 11 THEN TRSP.USABILITY_CODE WHEN 4 THEN LLSP.USABILITY_CODE WHEN 5 THEN LLSP.USABILITY_CODE
                   ELSE 0 END AS USABILITY_CODE,
  SM.CATCH_WEIGHT, SM.CATCH_COUNT
FROM GFBioSQL.dbo.B21_Samples SM
INNER JOIN GFBioSQL.dbo.B22_Specimens SP ON SM.SAMPLE_ID = SP.SAMPLE_ID
INNER JOIN GFBioSQL.dbo.SPECIES SPP ON SPP.SPECIES_CODE = SM.SPECIES_CODE
INNER JOIN GFBioSQL.dbo.Maturity_Convention MC ON SM.MATURITY_CONVENTION_CODE = MC.MATURITY_CONVENTION_CODE
INNER JOIN GFBioSQL.dbo.FISHING_EVENT FE ON FE.FISHING_EVENT_ID = SM.FISHING_EVENT_ID
LEFT OUTER JOIN GFBioSQL.dbo.TRAWL_SPECS AS TRSP ON FE.FISHING_EVENT_ID = TRSP.FISHING_EVENT_ID
LEFT OUTER JOIN GFBioSQL.dbo.LONGLINE_SPECS AS LLSP ON FE.FISHING_EVENT_ID = LLSP.FISHING_EVENT_ID
WHERE TRIP_SUB_TYPE_CODE NOT IN (2, 3) AND SPECIMEN_SEX_CODE IN (1, 2) AND SM.SAMPLE_SOURCE_CODE = 1 AND (CASE FE.GEAR_CODE WHEN 1 THEN TRSP.USABILITY_CODE WHEN 11 THEN TRSP.USABILITY_CODE WHEN 4 THEN LLSP.USABILITY_CODE WHEN 5 THEN LLSP.USABILITY_CODE
                   ELSE 0 END) IN (0,1,2,6) AND (FE.FE_PARENT_EVENT_ID IS NULL)) A

LEFT OUTER JOIN 
(SELECT TOP (100) PERCENT MC.MATURITY_CONVENTION_CODE AS MAT_CONV_CODE, SP.SPECIMEN_SEX_CODE, 
                  CASE SM.MATURITY_CONVENTION_CODE WHEN 1 THEN 3 WHEN 2 THEN 3 WHEN 3 THEN 3 WHEN 4 THEN 3 WHEN 5 THEN 4 WHEN 6 THEN 2 WHEN 7 THEN 3 WHEN 8 THEN 3 WHEN
                   10 THEN (CASE SP.SPECIMEN_SEX_CODE WHEN 1 THEN 90 WHEN 2 THEN 55 END) 
                  WHEN 11 THEN 3 WHEN 12 THEN 2 WHEN 13 THEN 3 WHEN 15 THEN 3 WHEN 16 THEN 2 WHEN 17 THEN 2 WHEN 18 THEN 3 WHEN 19 THEN 3 WHEN 20 THEN 2 WHEN 21 THEN 3
                   WHEN 22 THEN 2 WHEN 23 THEN 2 WHEN 24 THEN 3 WHEN 25 THEN 3 WHEN 26 THEN 3 ELSE NULL END AS MATURE_AT
FROM     GFBioSQL.dbo.B21_Samples AS SM INNER JOIN
                  GFBioSQL.dbo.B22_Specimens AS SP ON SM.SAMPLE_ID = SP.SAMPLE_ID INNER JOIN
                  GFBioSQL.dbo.MATURITY_CONVENTION AS MC ON SM.MATURITY_CONVENTION_CODE = MC.MATURITY_CONVENTION_CODE
GROUP BY MC.MATURITY_CONVENTION_CODE, 
                  CASE SM.MATURITY_CONVENTION_CODE WHEN 1 THEN 3 WHEN 2 THEN 3 WHEN 3 THEN 3 WHEN 4 THEN 3 WHEN 5 THEN 4 WHEN 6 THEN 2 WHEN 7 THEN 3 WHEN 8 THEN 3 WHEN
                   10 THEN (CASE SP.SPECIMEN_SEX_CODE WHEN 1 THEN 90 WHEN 2 THEN 55 END) 
                  WHEN 11 THEN 3 WHEN 12 THEN 2 WHEN 13 THEN 3 WHEN 15 THEN 3 WHEN 16 THEN 2 WHEN 17 THEN 2 WHEN 18 THEN 3 WHEN 19 THEN 3 WHEN 20 THEN 2 WHEN 21 THEN 3
                   WHEN 22 THEN 2 WHEN 23 THEN 2 WHEN 24 THEN 3 WHEN 25 THEN 3 WHEN 26 THEN 3 ELSE NULL END, SP.SPECIMEN_SEX_CODE
HAVING SP.SPECIMEN_SEX_CODE IN (1, 2)) B ON A.MATURITY_CONVENTION_CODE = B.MAT_CONV_CODE AND A.SEX = B.SPECIMEN_SEX_CODE