-- If any of this first call changes then update table in text (currently
--  in Andy's yeye15reproduce repo, will get moved to gfsynopsis), and make
--  sure you change any revised names in get-iphc-set-info.sql also
SELECT YEAR(TRIP_START_DATE) AS year,
	T.TRIP_ID AS tripID,
	FE.FISHING_EVENT_ID AS setID,
        BLOCK_DESIGNATION AS block,
	FE_MAJOR_LEVEL_ID AS setInTrip,
	C.SPECIES_CODE AS speciesCode,
	SPECIES_COMMON_NAME AS species,
	SUM(CATCH_WEIGHT) AS catchWeight,
	CATCH_COUNT AS catchCount,
	LGLSP_HOOKS_SET_COUNT AS hooksCount,
	SKATE_COUNT AS skatesCount,
        EFFECTIVE_SKATE AS effectSkate,
	SPECIES_CATEGORY_CODE AS speciesCat
  
FROM FISHING_EVENT FE
	INNER JOIN TRIP T ON FE.TRIP_ID = T.TRIP_ID 
	INNER JOIN TRIP_SURVEY TS ON TS.TRIP_ID = T.TRIP_ID
	INNER JOIN SURVEY S ON S.SURVEY_ID = TS.SURVEY_ID
	INNER JOIN FISHING_EVENT_CATCH FEC ON FEC.FISHING_EVENT_ID = FE.FISHING_EVENT_ID AND FEC.TRIP_ID = T.TRIP_ID
	INNER JOIN CATCH C ON C.CATCH_ID = FEC.CATCH_ID
	INNER JOIN LONGLINE_SPECS LGLSP ON LGLSP.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
	INNER JOIN IPHC_EFFECTIVE_SKATE ES ON ES.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
	INNER JOIN SPECIES SP ON SP.SPECIES_CODE = C.SPECIES_CODE
	
WHERE SURVEY_SERIES_ID = '14' AND FE_PARENT_EVENT_ID IS NULL

-- insert species here
GROUP BY TRIP_START_DATE,
	T.TRIP_ID,
	FE.FISHING_EVENT_ID,
    BLOCK_DESIGNATION,
	FE_MAJOR_LEVEL_ID ,
	C.SPECIES_CODE ,
	SPECIES_COMMON_NAME,
	CATCH_COUNT ,
	LGLSP_HOOKS_SET_COUNT ,
	SKATE_COUNT,
	EFFECTIVE_SKATE ,
	SPECIES_CATEGORY_CODE
ORDER BY year, T.TRIP_ID, FE.FISHING_EVENT_ID

