SELECT BEST_DATE,
	VESSEL_NAME,
	VESSEL_REGISTRATION_NUMBER,
	FISHERY_SECTOR,
	TRIP_ID,
	C.FISHING_EVENT_ID,
	FE_START_DATE,
	FE_END_DATE,
	SPECIES_CODE,
	GEAR,
	BEST_DEPTH,
	MAJOR_STAT_AREA_CODE,
	MINOR_STAT_AREA_CODE,
	LOCALITY_CODE,
	LATITUDE,
	LONGITUDE,
	ROUND(ISNULL(LANDED_KG, 0), 0) AS LANDED_KG,
	ROUND(ISNULL(DISCARDED_KG, 0),0) AS DISCARDED_KG,
	SUCCESS_NAME AS FE_SUCCESS
FROM GFFOS.dbo.GF_MERGED_CATCH C
	INNER JOIN GF_FE_TRAWL_SPECS TSP ON TSP.FISHING_EVENT_ID = C.FISHING_EVENT_ID 
	INNER JOIN SUCCESS S ON S.SUCCESS_CODE = TSP.SUCCESS_CODE
WHERE FE_END_DATE > FE_START_DATE AND 
	YEAR(FE_START_DATE) = YEAR(FE_END_DATE) AND
	FE_START_DATE IS NOT NULL AND
-- insert filters here
	FE_END_DATE IS NOT NULL	

