SELECT MC.MATURITY_CONVENTION_CODE AS MAT_CONV_CODE, MC.MATURITY_CONVENTION_DESC AS MAT_CONV_DESC, MD.SPECIMEN_SEX_CODE, MC.MATURITY_CONVENTION_MAXVALUE,
                  CASE MC.MATURITY_CONVENTION_CODE WHEN 1 THEN 3 WHEN 2 THEN 3 WHEN 3 THEN 3 WHEN 4 THEN 3 WHEN 7 THEN 3 WHEN 8 THEN 3 WHEN 11 THEN 3 WHEN 13 THEN
                   3 WHEN 15 THEN 3 WHEN 18 THEN 3 WHEN 19 THEN 3 WHEN 21 THEN 3 WHEN 24 THEN 3 WHEN 25 THEN 3 WHEN 26 THEN 3 WHEN 5 THEN 4 WHEN 6 THEN 2 WHEN 12 THEN 2
                   WHEN 16 THEN 2 WHEN 17 THEN 2 WHEN 20 THEN 2 WHEN 22 THEN 2 WHEN 23 THEN 2 WHEN 10 THEN (CASE MD.SPECIMEN_SEX_CODE WHEN 1 THEN 90 WHEN 2 THEN 55 ELSE NULL END)
                   ELSE NULL END AS MATURE_AT
FROM              GFBioSQL.dbo.MATURITY_CONVENTION AS MC INNER JOIN
				  GFBioSQL.dbo.MATURITY_DESCRIPTION AS MD ON MC.MATURITY_CONVENTION_CODE = MD.MATURITY_CONVENTION_CODE 
GROUP BY MC.MATURITY_CONVENTION_DESC, MC.MATURITY_CONVENTION_CODE, MD.SPECIMEN_SEX_CODE, MC.MATURITY_CONVENTION_MAXVALUE,
                  CASE MC.MATURITY_CONVENTION_CODE WHEN 1 THEN 3 WHEN 2 THEN 3 WHEN 3 THEN 3 WHEN 4 THEN 3 WHEN 7 THEN 3 WHEN 8 THEN 3 WHEN 11 THEN 3 WHEN 13 THEN
                   3 WHEN 15 THEN 3 WHEN 18 THEN 3 WHEN 19 THEN 3 WHEN 21 THEN 3 WHEN 24 THEN 3 WHEN 25 THEN 3 WHEN 26 THEN 3 WHEN 5 THEN 4 WHEN 6 THEN 2 WHEN 12 THEN 2
                   WHEN 16 THEN 2 WHEN 17 THEN 2 WHEN 20 THEN 2 WHEN 22 THEN 2 WHEN 23 THEN 2 WHEN 10 THEN (CASE MD.SPECIMEN_SEX_CODE WHEN 1 THEN 90 WHEN 2 THEN 55 END)
                   ELSE NULL END
ORDER BY MAT_CONV_CODE
